### ISSUE TITLE
Error on submit in prescreening_results

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/rva-screening#156]
We reached this error two when Kara attempted to run through pre-screening today. 
Not sure why. 

She had used the back button to go back and forth a few times between `new_prescreening/` and `prescreening_basic/` and that may have affected it.
She then started over again and tried different answers, and got it to work. My guess is that it either had to do with using the back button or giving specific answers. 

Needs some manual follow-up testing of using back button and entering different answers.

Here's the stack trace (you can see the back and forth, and then finally a successful 200 at prescreening_results):

``` python
127.0.0.1 - - [02/Jun/2015 10:41:13] "GET /patient_details/1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:44:24] "GET /new_prescreening/1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:45:55] "POST /new_prescreening/1 HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:45:55] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:46:08] "GET /new_prescreening/1 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:46:39] "POST /new_prescreening/1 HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:46:39] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:46:51] "GET /new_prescreening HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:46:53] "POST /new_prescreening HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:46:53] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "POST /prescreening_basic HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bgolder/projects/screener/rva/app/views.py", line 457, in prescreening_results
    services = calculate_pre_screen_results(),
TypeError: calculate_pre_screen_results() takes exactly 1 argument (0 given)
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:06] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:12] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:31] "GET /new_prescreening HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:33] "POST /new_prescreening HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:47:33] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "POST /prescreening_basic HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/bgolder/projects/screener/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/Users/bgolder/projects/screener/rva/app/views.py", line 457, in prescreening_results
    services = calculate_pre_screen_results(),
TypeError: calculate_pre_screen_results() takes exactly 1 argument (0 given)
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:42] "GET /prescreening_results?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:44] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:44] "GET /new_prescreening HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:47:55] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:48:00] "GET /search_new HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:48:02] "GET /new_patient HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:48:05] "GET /new_prescreening HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:48:07] "POST /new_prescreening HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:48:07] "GET /prescreening_basic HTTP/1.1" 200 -
127.0.0.1 - - [02/Jun/2015 10:48:17] "POST /prescreening_basic HTTP/1.1" 302 -
127.0.0.1 - - [02/Jun/2015 10:48:17] "GET /prescreening_results HTTP/1.1" 200 -
```

**Comment by esmithayer** [comment]
This is from the "prescreen this patient" workflow--kind of forgot that was still there. I can fix this today.
